name: 'Angular Canary'
description: 'Build'
author: 'Jared Szechy'
inputs:
  github_token:
    description: Auth token for github repos
    required: true
  bp_github_token:
    description: Auth token for BP github repos
    required: true
  bucket:
    description: S3 bucket name
    required: true
outputs:
  destination:
    description: S3 URI for assets
runs:
  using: node10
  main: lib/main.js
